image: docker:latest

services:
  - docker:dind

variables:
  USER_SITE_DOCKER_IMAGE_NAME: registry.gitlab.com/idimzo/idimzo_user_site_frontend
  USER_SITE_DOCKER_IMAGE_TAG: latest
  USER_SITE_CONTAINER_NAME: idimzo_user_site
  USER_SITE_NETWORK_NAME: idimzo_network

stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  image: docker:dind
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $USER_SITE_DOCKER_IMAGE_NAME:$USER_SITE_DOCKER_IMAGE_TAG .
    - docker push $USER_SITE_DOCKER_IMAGE_NAME:$USER_SITE_DOCKER_IMAGE_TAG
  after_script:
    - docker images
  only:
    - main
deploy:
  stage: deploy
  when: manual
  tags:
    - ownrunner
  before_script:
    - apk add --no-cache openssh-client sshpass
  script:
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_IP "docker pull $USER_SITE_DOCKER_IMAGE_NAME:$USER_SITE_DOCKER_IMAGE_TAG"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_IP "docker stop $USER_SITE_CONTAINER_NAME || true"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_IP "docker rm $USER_SITE_CONTAINER_NAME || true"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_IP "docker run -d --name $USER_SITE_CONTAINER_NAME --network $USER_SITE_NETWORK_NAME -p 3000:3000 --add-host host.docker.internal:host-gateway $USER_SITE_DOCKER_IMAGE_NAME:$USER_SITE_DOCKER_IMAGE_TAG"
  only:
    - main

